version: "3"

services:
  db:
    image: jsurf/rpi-mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - "./nc_config/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  redis:
    image: redis
    restart: always

  app:
    image: nextcloud
    restart: always
    volumes:
      - "./nc_config/nextcloud:/var/www/html"
    environment:
      #   - VIRTUAL_HOST=
      #   - LETSENCRYPT_HOST=
      #   - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud
    restart: always
    volumes:
      - "./nc_config/nextcloud:/var/www/html"
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 28080:80
    volumes:
      - "./nc_config/nextcloud:/var/www/html:ro"
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
      - default

networks:
  proxy-tier:
